//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blogcum.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Bloglar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Bloglar()
        {
            this.Yorumlar = new HashSet<Yorumlar>();
        }
    
        public int BlogYazisiID { get; set; }

        [DisplayName("Blog Yazýnýz"), Required(ErrorMessage = "Bu alan adý bos gecilemez.")]
        public string BlogYazisi { get; set; }

        [DisplayName("Kategoriniz"), Required(ErrorMessage = "Bu alan adý bos gecilemez."),
            MaxLength(20, ErrorMessage = "20'den fazla karakter giremezsiniz")]
        public string Kategori { get; set; }

        public int BlogcuID { get; set; }
    
        public virtual Blogcular Blogcular { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Yorumlar> Yorumlar { get; set; }
    }
}
