//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blogcum.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Blogcular
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Blogcular()
        {
            this.Bloglar = new HashSet<Bloglar>();
            this.Iletisim = new HashSet<Iletisim>();
            this.Yorumlar = new HashSet<Yorumlar>();
        }
    
        public int BlogcuID { get; set; }

        [DisplayName("Adýnýz"),Required(ErrorMessage = "Bu alan adý bos gecilemez."),
            MaxLength(50,ErrorMessage ="50'den fazla karakter giremezsiniz")]
        public string BlogcuAdi { get; set; }

        [DisplayName("Soyadýnýz"),Required(ErrorMessage = "Bu alan adý bos gecilemez."),
            MaxLength(50, ErrorMessage = "50'den fazla karakter giremezsiniz")]
        public string BlogcuSoyadi { get; set; }
       

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bloglar> Bloglar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Iletisim> Iletisim { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Yorumlar> Yorumlar { get; set; }
       
    }
}
