//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blogcum.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Iletisim
    {
        public int IletiID { get; set; }

        [DisplayName("Ýletiniz"), Required(ErrorMessage = "Bu alan adý bos gecilemez."),
            MaxLength(100, ErrorMessage = "100'den fazla karakter giremezsiniz")]
        public string Ileti { get; set; }

        [DisplayName("Konu Giriniz"), Required(ErrorMessage = "Bu alan adý bos gecilemez."),
            StringLength(10, ErrorMessage = "10'dan fazla karakter giremezsiniz")]
        public string Konu { get; set; }

        public int BlogcuID { get; set; }
    
        public virtual Blogcular Blogcular { get; set; }
    }
}
