//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blogcum.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Yorumlar
    {
        public int YorumID { get; set; }

        [DisplayName("Yorumunuz"), Required(ErrorMessage = "Bu alan adý bos gecilemez."),
            MaxLength(100, ErrorMessage = "100'den fazla karakter giremezsiniz")]
        public string Yorum { get; set; }

        public int BlogcuID { get; set; }
        
        public int BlogYazisiID { get; set; }
    
        public virtual Blogcular Blogcular { get; set; }
        public virtual Bloglar Bloglar { get; set; }
    }
}
